export const PSYCHOANALYSIS_VOCABULARY = [
  'psicanálise',
  'psicanalista',
  'analisando',
  'analisante',
  'transferência',
  'contratransferência',
  'pulsão',
  'significante',
  'significado',
  'recalque',
  'recalcamento',
  'sublimação',
  'narcisismo',
  'Édipo',
  'complexo de Édipo',
  'castração',
  'falo',
  'fálico',
  'libido',
  'catexia',
  'objeto parcial',
  'objeto transicional',
  'Winnicott',
  'Lacan',
  'Freud',
  'Klein',
  'Bion',
  'Ferenczi',
  'Abraham',
  'Melanie Klein',
  'Jacques Lacan',
  'Sigmund Freud',
  'Real',
  'Simbólico',
  'Imaginário',
  'RSI',
  'grande Outro',
  'petit a',
  'objeto a',
  'gozo',
  'jouissance',
  'demanda',
  'desejo',
  'sujeito',
  'eu ideal',
  'ideal do eu',
  'supereu',
  'superego',
  'id',
  'ego',
  'ato falho',
  'lapso',
  'sonho',
  'interpretação',
  'associação livre',
  'atenção flutuante',
  'setting',
  'enquadre',
  'manejo',
  'acting out',
  'passagem ao ato',
  'resistência',
  'defesa',
  'mecanismos de defesa',
  'projeção',
  'introjeção',
  'identificação projetiva',
  'cisão',
  'splitting',
  'clivagem',
  'foraclusão',
  'forclusão',
  'denegação',
  'Verneinung',
  'Verwerfung',
  'Verdrängung',
  'neurose',
  'psicose',
  'perversão',
  'histeria',
  'obsessão',
  'fobia',
  'angústia',
  'sintoma',
  'formação de compromisso',
  'elaboração',
  'perlaboração',
  'Durcharbeitung',
  'supervisão clínica',
  'clínica psicanalítica',
  'escuta',
  'escuta analítica',
  'posição depressiva',
  'posição esquizoparanoide',
  'estádio do espelho',
  'Nome-do-Pai',
  'metáfora paterna',
  'PCO',
  'AVA',
];
